config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # authenticated :user do
  #   root 'self_tests#new', as: :authenticated_root
  # end

  get 'terms', to: 'main#terms'
  root 'main#index'

  resources :social_distances, only: %i[new create show]
  resources :self_tests, only: %i[new create]
  resources :results, only: %i[index]
  resources :users_dashboards, only: %i[index]
  resources :monitorings, only: %i[show]
end

app/models/self_test.rb
class SelfTest < ApplicationRecord
  belongs_to :user, optional: true

  @checked_message = " - #{I18n.t(:checked_message).capitalize}"
  @invalid = " - #{I18n.t(:checked_message).capitalize}"

  validates :self_test_zip_code, presence: true

  validates :fever,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :shortness_of_breath,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :tiredness,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :cough,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :sore_throat,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :vomit,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :diarrhea,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :feel_fine,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :how_long_feeling,
  presence: true, format: { with: /\A[0-2]\z/,
                            message: @invalid_message }
  validates :diabetes,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :high_pressure,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :asthma_bronchitis,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :heart_disease,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :chronic_respiratory_disease,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :chronic_kidney_disease,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :depression,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :immunosuppression,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :other_symptoms,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :no_additional_symptoms,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :clinic,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :depression,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :ambulatory,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :emergency_room,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :didnt_look_for_help,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :covid_test,
  presence: true, format: { with: /\A[0-2]\z/,
                            message: @invalid_message }
end

app/controllers/self_tests_controller.rb
class SelfTestsController < ApplicationController
  before_action :authenticate_user!

  def new
    @self_test = SelfTest.new
  end

  def create
    @self_test = SelfTest.new(self_test_params)
    @self_test.result = add_result_to_self_test
    return redirect_to results_path if @self_test.save

    render :new
  end

  private

  def self_test_params
    params
      .require(:self_test)
      .permit(:fever, :shortness_of_breath, :tiredness, :cough, :sore_throat,
              :vomit, :feel_fine, :how_long_feeling, :diabetes, :high_pressure,
              :asthma_bronchitis, :heart_disease, :depression, :other_symptoms,
              :chronic_respiratory_disease, :chronic_kidney_disease, :diarrhea,
              :immunosuppression, :no_additional_symptoms, :health_service_unit,
              :clinic, :ambulatory, :emergency_room, :didnt_look_for_help,
              :covid_test).merge(user_id: current_user.id, result: nil,
                                 self_test_zip_code: current_user.user_zip_code)
  end

  def self_test_alert_fine
    return '' if @self_test.nil?
    return 0 if @self_test.feel_fine == 1

    1
  end

  def self_test_alert_attention
    return '' if @self_test.nil?
    return 1 if @self_test.no_additional_symptoms == 1
    return 1 if @self_test.didnt_look_for_help == 1
    return 1 if @self_test.covid_test == 2

    0
  end

  def self_test_alert_critical
    return '' if @self_test.nil?

    is_critical = 0
    is_critical += 1 if @self_test.fever == 1
    is_critical += 1 if @self_test.shortness_of_breath == 1
    is_critical += 1 if @self_test.tiredness == 1
    return 2 if is_critical == 3

    0
  end

  def self_test_result
    return 2 if self_test_alert_critical == 2
    return 1 if self_test_alert_attention == 1
    return 0 if self_test_alert_fine.to_i.zero?

    1
  end

  def add_result_to_self_test
    self_test_result
  end
end

app/views/self_tests/new.html.erb
<h3><%= t(:form_self_test).capitalize %></h3>

<p><%= t(:user).capitalize %>: <%= current_user.email %><p>

<% if @self_test.errors.any? %>
  <% @self_test.errors.full_messages.each do |message| %>
     <%= javascript_tag "M.toast({html: '#{t(message).capitalize }'}, 4000)" unless message.nil? %>
  <% end %>
<% end %>

<%= form_with url: self_tests_path, model: @self_test,  local: true do |f| %>

  <p><%= f.label '', t(:any_symptoms).capitalize %></p>

  <%= f.label :feel_fine , t(:feel_fine).capitalize do %>
    <%= t(:feel_fine).capitalize %>
    <br>
    <%= f.check_box :feel_fine, type:"checkbox" %>
    <span>
  <% end %>
  <hr>
  
  <div id='hide_if_fine' style=" display: flex; align-content: flex-start; flex-grow: 1; flex-wrap: wrap">
    
    <span style="display: flex; flex-wrap: wrap;">

      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :fever , t(:fever).capitalize, style:"flex-grow: 1;" do %>
          <%= t(:fever).capitalize %>
          <br>
          <%= f.check_box :fever, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :shortness_of_breath , t(:shortness_of_breath).capitalize, style:"flex-grow: 1;" do %>
          <%= t(:shortness_of_breath).capitalize %>
          <br>
          <%= f.check_box :shortness_of_breath, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :tiredness , t(:tiredness).capitalize,  style:"flex-grow: 1;" do %>
          <%= t(:tiredness).capitalize %>
          <br>
          <%= f.check_box :tiredness, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :cough , t(:cough).capitalize,  style:"flex-grow: 1;" do %>
          <%= t(:cough).capitalize %>
          <br>
          <%= f.check_box :cough, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :sore_throat , t(:sore_throat).capitalize,  style:"flex-grow: 1;" do %>
          <%= t(:sore_throat).capitalize %>
          <br>
          <%= f.check_box :sore_throat, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :vomit , t(:vomit).capitalize,  style:"flex-grow: 1;" do %>
          <%= t(:vomit).capitalize %>
          <br>
          <%= f.check_box :vomit, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style='min-width: 7em; margin-right: 2vw'>
        <%= f.label :diarrhea , t(:diarrhea).capitalize,  style:"flex-grow: 1;" do %>
          <%= t(:diarrhea).capitalize %>
          <br>
          <%= f.check_box :diarrhea, type:"checkbox" %>
          <span>
        <% end %>
      </div>
    
    </span>

    <div style="margin-bottom: 1em; margin-top: 1em; flex-grow: 8">
      <%= f.label :how_long_feeling, t(:how_long_feeling).capitalize %>
      <%= f.select(:how_long_feeling, [[t(:first_week_range).capitalize, 0], [t(:second_week_range).capitalize, 1], [t(:more_two_weeks_range).capitalize, 2]], {}, { :style => 'display: block; margin-top: 0;' }) %>
    </div>
      
    <span style="display: flex; flex-wrap: wrap;">

      <div style="min-width: 100%; margin-bottom: 1em; margin-top: 1em;">
        <%= f.label '', t(:additional_symptoms).capitalize %>
      </div>
        
      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :diabetes , t(:diabetes).capitalize, style: "flex-grow: 1" do %>
          <%= t(:diabetes).capitalize %>
          <br>
          <%= f.check_box :diabetes, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :high_pressure , t(:high_pressure).capitalize, style: "flex-grow: 1" do %>
          <%= t(:high_pressure).capitalize %>
          <br>
          <%= f.check_box :high_pressure, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :asthma_bronchitis , t(:asthma_bronchitis).capitalize, style: "flex-grow: 1" do %>
          <%= t(:asthma_bronchitis).capitalize %>
          <br>
          <%= f.check_box :asthma_bronchitis, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :heart_disease , t(:heart_disease).capitalize, style: "flex-grow: 1" do %>
          <%= t(:heart_disease).capitalize %>
          <br>
          <%= f.check_box :heart_disease, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :chronic_respiratory_disease , t(:chronic_respiratory_disease).capitalize, style: "flex-grow: 1" do %>
          <%= t(:chronic_respiratory_disease).capitalize %>
          <br>
          <%= f.check_box :chronic_respiratory_disease, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :chronic_kidney_disease , t(:chronic_kidney_disease).capitalize, style: "flex-grow: 1" do %>
          <%= t(:chronic_kidney_disease).capitalize %>
          <br>
          <%= f.check_box :chronic_kidney_disease, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :depression , t(:depression).capitalize, style: "flex-grow: 1" do %>
          <%= t(:depression).capitalize %>
          <br>
          <%= f.check_box :depression, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :immunosuppression , t(:immunosuppression).capitalize, style: "flex-grow: 1" do %>
          <%= t(:immunosuppression).capitalize %>
          <br>
          <%= f.check_box :immunosuppression, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :other_symptoms , t(:other_symptoms).capitalize, style: "flex-grow: 1" do %>
          <%= t(:other_symptoms).capitalize %>
          <br>
          <%= f.check_box :other_symptoms, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 11em; margin-right: 2vw">
        <%= f.label :no_additional_symptoms , t(:no_additional_symptoms).capitalize, style: "flex-grow: 1" do %>
          <%= t(:no_additional_symptoms).capitalize %>
          <br>
          <%= f.check_box :no_additional_symptoms, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
    </span>

    <span style="display: flex; flex-wrap: wrap;">

      <div style="min-width: 100%; margin-bottom: 1em; margin-top: 1em;">
        <%= f.label '', t(:sought_health_service).capitalize %>
      </div>

      <div style="min-width: 5.5em; margin-right: 2vw">
        <%= f.label :health_service_unit , t(:health_service_unit).capitalize do %>
          <%= t(:health_service_unit).capitalize %>
          <br>
          <%= f.check_box :health_service_unit, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 5.5em; margin-right: 2vw">
        <%= f.label :clinic , t(:clinic).capitalize do %>
          <%= t(:clinic).capitalize %>
          <br>
          <%= f.check_box :clinic, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 5.5em; margin-right: 2vw">
        <%= f.label :ambulatory , t(:ambulatory).capitalize do %>
          <%= t(:ambulatory).capitalize %>
          <br>
          <%= f.check_box :ambulatory, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 5.5em; margin-right: 2vw">
        <%= f.label :emergency_room , t(:emergency_room).capitalize do %>
          <%= t(:emergency_room).capitalize %>
          <br>
          <%= f.check_box :emergency_room, type:"checkbox" %>
          <span>
        <% end %>
      </div>
      
      <div style="min-width: 5.5em; margin-right: 2vw">
        <%= f.label :didnt_look_for_help , t(:didnt_look_for_help).capitalize do %>
          <%= t(:didnt_look_for_help).capitalize %>
          <br>
          <%= f.check_box :didnt_look_for_help, type:"checkbox" %>
          <span>
        <% end %>
      </div>

      <div style="min-width: 100%; margin-bottom: 1em; margin-top: 1em; flex-grow: 1">
        <%= f.label :covid_test, t(:no_test_covid).capitalize %>
        <%= f.select(:covid_test, [[t(:less_than_seven_days).capitalize ,0], [t(:more_than_seven_days).capitalize ,1], [t(:covid_test).capitalize ,2]], {}, { :style => 'display: block; margin-top: 0em;' }) %>
      </div>

    </span>
  </div>

  <div class='row center'>
    <%= f.button t(:save).capitalize, class: "white-text actions btn-large waves-effect" %>
  </div>

<% end %>

<script>
  let element = document.querySelector('#self_test_feel_fine')
    element.addEventListener('click', (e)=>{
      let my_span = document.querySelector('#hide_if_fine')

      if(my_span.style.visibility == 'visible' || !my_span.style.visibility){
        my_span.style.visibility= 'hidden';
        my_span.style.display= 'none'

      }else{
        my_span.style.visibility= 'visible';
        my_span.style.display= 'block'
      }
    })
</script>