config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # authenticated :user do
  #   root 'self_tests#new', as: :authenticated_root
  # end

  get 'terms', to: 'main#terms'
  root 'main#index'

  resources :social_distances, only: %i[new create show]
  resources :self_tests, only: %i[new create]
  resources :results, only: %i[index]
  resources :users_dashboards, only: %i[index]
  resources :monitorings, only: %i[show]
end

app/models/social_distance.rb
class SocialDistance < ApplicationRecord
  belongs_to :user, optional: true

  @checked_message = " - #{I18n.t(:checked_message).capitalize}"
  @one_to_99_message = " - #{I18n.t(:one_to_99_message).capitalize}"
  @zero_to_99_message = " - #{I18n.t(:zero_to_99_message).capitalize}"

  validates :social_distance_zip_code, presence: true

  validates :how_many_residents,
  presence: true, format: { with: /\A[1-9][0-9]?\z/,
                            message: @one_to_99_message }
  validates :residence_type,
  presence: true, format: { with: /\A[0-2]\z/,
                            message: @checked_message }
  validates :bedrooms,
  presence: true, format: { with: /\A[1-9][0-9]?\z/,
                            message: @one_to_99_message }
  validates :bathrooms,
  presence: true, format: { with: /\A[1-9][0-9]?\z/,
                            message: @one_to_99_message }
  validates :rooms,
  presence: true, format: { with: /\A[1-9][0-9]?\z/,
                            message: @one_to_99_message }
  validates :many_contacts,
  presence: true, format: { with: /\A[0-9][0-9]?\z/,
                            message: @zero_to_99_message }
  validates :been_outdoor,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :many_times_outdoor,
  presence: true, format: { with: /\A[0-9][0-9]?\z/,
                            message: @zero_to_99_message }
  validates :supermarket,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :pharmacy,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :health_service,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :commerce,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :market,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :workplace,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :other_places,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :public_transportation,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :many_transportations,
  presence: true, format: { with: /\A[0-9][0-9]?\z/,
                            message: @zero_to_99_message }
  validates :bus,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :subway, presence: true, format: { with: /\A[0-1]\z/,
                                               message: @checked_message }
  validates :train, presence: true, format: { with: /\A[0-1]\z/,
                                              message: @checked_message }
  validates :transport_apps,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
  validates :car, presence: true, format: { with: /\A[0-1]\z/,
                                            message: @checked_message }
  validates :bicycle, presence: true, format: { with: /\A[0-1]\z/,
                                                message: @checked_message }
  validates :taxi, presence: true, format: { with: /\A[0-1]\z/,
                                             message: @checked_message }
  validates :other_transportations,
  presence: true, format: { with: /\A[0-1]\z/,
                            message: @checked_message }
end

app/controllers/social_distances_controller.rb
class SocialDistancesController < ApplicationController
  before_action :generate_new_social_distance, only: [:create]
  def new
    @social_distance = SocialDistance.new
  end

  def create
    if user_signed_in? && (@social_distance.user_id = current_user.id)
      set_zipcode
      negative_and_flash
      return redirect_to users_dashboards_path :index if @social_distance.save

    else
      @social_distance.user_id = 1
      negative_and_flash
      return redirect_to new_user_registration_path if @social_distance.valid?

    end
    render :new
  end

  private

  def social_distance_params
    params
      .require(:social_distance)
      .permit(:how_many_residents, :residence_type,
              :bedrooms, :bathrooms, :rooms, :many_contacts, :been_outdoor,
              :many_times_outdoor, :supermarket, :pharmacy, :health_service,
              :commerce, :market, :workplace, :other_places,
              :public_transportation, :many_transportations, :bus, :subway,
              :train, :transport_apps, :car, :bicycle, :taxi,
              :other_transportations)
      .merge(social_distance_zip_code: generate_zip_code)
  end

  def generate_new_social_distance
    @social_distance = SocialDistance.new(social_distance_params)
  end

  def generate_flash
    flash[:tmp] = @social_distance if @social_distance.valid?
  end

  def generate_zip_code
    return current_user.user_zip_code if user_signed_in?

    '01001000'
  end

  def set_zipcode
    @social_distance.social_distance_zip_code = current_user.user_zip_code
  end

  def protect_from_negative
    return if @social_distance.many_transportations.nil?

    is_checked = @social_distance.public_transportation == 1
    is_negative = @social_distance.many_transportations < 1
    @social_distance.many_transportations = -1 if is_checked && is_negative
  end

  def negative_and_flash
    generate_flash
    protect_from_negative
  end
end

app/views/social_distances/new.html.erb
  <h3><%= t(:social_distance).capitalize %></h3>

<% if !@social_distance.nil? && @social_distance.errors.any? %>
  <% @social_distance.errors.full_messages.each do |message| %>
    <p><% message.capitalize %></p>
    <p><%= javascript_tag "M.toast({html: '#{message.capitalize}'}, 4000)" unless message.nil? %><p>
  <% end %>
<% end %>

<%= form_with url: social_distances_path, model: @social_distance, method: 'POST', local: true do |f| %>
  <p>
    <%= f.label :how_many_residents, t(:how_many_residents).capitalize %>
    <%= f.number_field :how_many_residents %>
  </p>

  <p>
    <%= f.label :residence_type, t(:residence_type).capitalize %>
    <%= f.select(:residence_type, [[t(:house),0], [t(:apartment),1], [t(:others),2]], {}, { :style => 'display: block; margin-top: 0em;' }) %>
  </p>

  <p>
    <%= f.label :bedrooms, t(:how_many_bedrooms).capitalize %>
    <%= f.number_field :bedrooms %>
  </p>

  <p>
    <%= f.label :bathrooms, t(:how_many_bathrooms).capitalize %>
    <%= f.number_field :bathrooms %>
  </p>

  <p>
    <%= f.label :rooms, t(:how_many_rooms).capitalize %>
    <%= f.number_field :rooms %>
  </p>

  <p>
    <%= f.label :many_contacts, t(:many_contacts).capitalize %>
    <%= f.number_field :many_contacts %>
  </p>

  <p>
    <%= f.label :been_outdoor , t(:been_outdoor).capitalize do %>
      <%= t(:been_outdoor).capitalize %>
      <br>
      <% if !params[:social_distance].nil? && params[:social_distance][:been_outdoor] == '1'%>
        <%= f.check_box :been_outdoor, type:"checkbox", checked: true %>
      <% else %>
        <%= f.check_box :been_outdoor, type:"checkbox", checked: false %>
      <% end %>
  <span>
    <% end%>
  </p>
  
  <% if !params[:social_distance].nil? && params[:social_distance][:been_outdoor] == '1'%>
    <span id='hide_all_under_if_fine' style="display: block; visibility: visible;">
  <% else %>
    <span id='hide_all_under_if_fine' style="display: none; visibility: hidden;">
  <% end %>


  <%= f.label :many_times_outdoor, t(:many_times_outdoor).capitalize %>
  <%= f.number_field :many_times_outdoor %>



    <div style="display: flex; flex-wrap: wrap;">

      <p style="min-width: 100%; margin: 2em 0 0 0; flex-grow: 1;">
        <%= f.label '', t(:where).capitalize, style: 'flex-grow:1' %>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :supermarket , t(:supermarket).capitalize do %>
          <%= t(:supermarket).capitalize %>
          <br>
          <%= f.check_box :supermarket, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :pharmacy , t(:pharmacy).capitalize do %>
          <%= t(:pharmacy).capitalize %>
          <br>
          <%= f.check_box :pharmacy, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :health_service , t(:health_service).capitalize do %>
          <%= t(:health_service).capitalize %>
          <br>
          <%= f.check_box :health_service, type:"checkbox" %>
          <span>
        <% end%>
        <br>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :commerce , t(:commerce).capitalize do %>
          <%= t(:commerce).capitalize %>
          <br>
          <%= f.check_box :commerce, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :market , t(:market).capitalize do %>
          <%= t(:market).capitalize %>
          <br>
          <%= f.check_box :market, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :workplace , t(:workplace).capitalize do %>
          <%= t(:workplace).capitalize %>
          <br>
          <%= f.check_box :workplace, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 6.8em; margin-right: 0vw;">
        <%= f.label :other_places , t(:other_places).capitalize do %>
          <%= t(:other_places).capitalize %>
          <br>
          <%= f.check_box :other_places, type:"checkbox" %>
          <span>
        <% end%>
      </p>

    </div>








    <%= f.label :public_transportation , t(:public_transportation).capitalize do %>
      <%= t(:public_transportation).capitalize %>
      <br>
      <%= f.check_box :public_transportation, type:"checkbox" %>
      <span>
    <% end%>
    
    <p>
      <%= f.label :many_transportations, t(:many_transportations).capitalize %>
      <%= f.number_field :many_transportations %>
    </p>







    <div style="display: flex; flex-wrap: wrap;">

      <p style="min-width: 100%; margin: 2em 0 0 0; flex-grow: 1;">
        <%= f.label '', t(:transport_type).capitalize %>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :bus , t(:bus).capitalize do %>
          <%= t(:bus).capitalize %>
          <br>
          <%= f.check_box :bus, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :subway , t(:subway).capitalize do %>
          <%= t(:subway).capitalize %>
          <br>
          <%= f.check_box :subway, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :train , t(:train).capitalize do %>
          <%= t(:train).capitalize %>
          <br>
          <%= f.check_box :train, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :transport_apps , t(:transport_apps).capitalize do %>
          <%= t(:transport_apps).capitalize %>
          <br>
          <%= f.check_box :transport_apps, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :car , t(:car).capitalize do %>
          <%= t(:car).capitalize %>
          <br>
          <%= f.check_box :car, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :bicycle , t(:bicycle).capitalize do %>
          <%= t(:bicycle).capitalize %>
          <br>
          <%= f.check_box :bicycle, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :taxi , t(:taxi).capitalize do %>
          <%= t(:taxi).capitalize %>
          <br>
          <%= f.check_box :taxi, type:"checkbox" %>
          <span>
        <% end%>
      </p>

      <p style="min-width: 7.4em; margin-right: 1vw;">
        <%= f.label :other_transportations , t(:other_transportations).capitalize do %>
          <%= t(:other_transportations).capitalize %>
          <br>
          <%= f.check_box :other_transportations, type:"checkbox" %>
          <span>
        <% end%>
      </p>
    </div>
    
  </span>


  

  <div class='row center' style="margin-top: 2em;">
    <%= f.button t(:save).capitalize, class: "white-text actions btn-large waves-effect" %>
  </div>
<% end %>

<script>
  let element = document.querySelector('#social_distance_been_outdoor')
  let my_span = document.querySelector('#hide_all_under_if_fine')
  let many_times_outdoor = document.querySelector('#social_distance_many_times_outdoor')
  let many_transportations = document.querySelector('#social_distance_many_transportations')

  element.addEventListener('change', (e)=>{
    

    if(my_span.style.visibility == 'visible' || !my_span.style.visibility){
      my_span.style.display= 'block';
      my_span.style.visibility= 'hidden';
      my_span.style.widht= '0px';
      my_span.style.height= '0px';


      reset_value(many_times_outdoor)
      reset_value(many_transportations)

    }else{
      my_span.style.display= 'block';
      my_span.style.visibility= 'visible';
      my_span.style.widht= 'auto';
      my_span.style.height= 'auto';
    }
  })

  cannot_be_negative_list = document.querySelectorAll('input[type=number]')
  
  not_negative(cannot_be_negative_list)
  
  function not_negative(list){
    list.forEach((element)=>{
      if(element.value < 0 )element.value = 0;
      element.addEventListener('change', (e)=>{
        if(element.value < 0 ){
          element.value = 0
        }
      });
    });
  }

  function reset_value(element){
    element.value = 0
  }
</script>