config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # authenticated :user do
  #   root 'self_tests#new', as: :authenticated_root
  # end

  get 'terms', to: 'main#terms'
  root 'main#index'

  resources :social_distances, only: %i[new create show]
  resources :self_tests, only: %i[new create]
  resources :results, only: %i[index]
  resources :users_dashboards, only: %i[index]
  resources :monitorings, only: %i[show]
end

app/views/shared/_footer.html.erb
<footer class="page-footer teal lighten-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><%= link_to  t(:terms).capitalize, terms_path, class:"grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright center align">
    <div class="container">
    © 2020 Copyright Text
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav>
    <div class="nav-wrapper teal teal lighten-1">
      <div class="brand-logo">
      <%= link_to root_url do %>
      <i class="material-icons">home</i><span style="font-size:0.8em;"><%= t(:home)%></span>
      <% end %>
      </div>


      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      
      <ul class="right hide-on-med-and-down">
        
        <li><%= link_to  t(:dashboard).capitalize, users_dashboards_path %></li>
        <li><%= link_to  t(:terms).capitalize, terms_path %></li>
        <li><%= link_to(t(:logout).capitalize, destroy_user_session_path, method: :delete) %></li>
      </ul>
    </div>
  </nav>

 
  <ul class="sidenav" id="mobile-demo">

    <li><%= link_to  t(:dashboard).capitalize, users_dashboards_path %></li>
    <li><%= link_to  t(:social_distance).capitalize, new_social_distance_path %></li>
    <li><%= link_to  t(:self_test).capitalize, new_self_test_path %></li>
    <li><%= link_to  t(:monitoring).capitalize, monitoring_path(current_user.id) %></li>
    <li><%= link_to  t(:terms).capitalize, terms_path %></li>
    <li><%= link_to t(:edit_registration).capitalize,edit_user_registration_path %></li>
    <li><%= link_to(t(:logout).capitalize, destroy_user_session_path, method: :delete) %></li>
    
  </ul>

app/views/shared/_notice_and_alert.html.erb
<% if notice %>
  <%= javascript_tag "M.toast({html: '#{notice}'}, 4000)" unless notice.nil? %>
<% end %>
<% if alert %>
  <%= javascript_tag "M.toast({html: '#{alert}'}, 4000)" unless alert.nil? %>
<% end %>